### ISSUE TITLE
Show version or commit in Frontend

### ISSUE THREAD

**Issue by MvBonin** [CADmium-Co/CADmium#102]
[cadmium-co.github.io/CADmium/](https://cadmium-co.github.io/CADmium/)
This is very nice, because we can just test the Application there, but it would be nice to have an Information about which version / commit this is built from. Users could refer to the Version if they find bugs etc.

Maybe this could be done via env variables?

**Comment by MattFerraro** [comment]
Agreed, this would be an awesome feature!
