### ISSUE TITLE
Scroll Bars on the demo 

### ISSUE THREAD

**Issue by drewbt** [CADmium-Co/CADmium#11]
![image](https://github.com/MattFerraro/CADmium/assets/417978/f6d25c1c-7170-4283-bd56-3c629d93e25b)

The overall page needs to lose the horizontal and vertical scroll bars in google chrome.

**Comment by MattFerraro** [comment]
Oh gosh that's not good!

Strangely I can't reproduce this effect on my mac version of chrome. what OS are you using?

<img width="1440" alt="Screenshot 2024-05-23 at 9 53 37 AM" src="https://github.com/CADmium-Co/CADmium/assets/1302431/04a37be2-3331-48d8-a6ac-000471afffad">

**Comment by drewbt** [comment]
Chrome on windows

**Comment by av8ta** [comment]
![image](https://github.com/CADmium-Co/CADmium/assets/17036768/3d387e73-397a-4569-8e73-64f0b141992b)

I'm not seeing it in linux brave (chromium under the hood) either

**Comment by av8ta** [comment]
Not seeing scroll bars in win 10 chromium also.

**Comment by av8ta** [comment]
Fixed in https://github.com/CADmium-Co/CADmium/pull/12
