### ISSUE TITLE
ERROR 404 link in "about" and README

### ISSUE THREAD

**Issue by basketshoe** [CADmium-Co/CADmium#18]
This link (https://mattferraro.github.io/CADmium/) redirects to a 404. It is present both in the about section and in the readme It should be changed to https://cadmium-co.github.io/CADmium/

**Comment by MattFerraro** [comment]
good catch! a side effect of migrating the repository to an org earlier this morning. Fixed!

**Comment by basketshoe** [comment]
np, also remember to change it from README (line 38)

> ```If you're just trying to kick the tires, [click here](https://MattFerraro.github.io/CADmium/) to view the live web demo.```

And everything else that contains your old nickname

**Comment by MattFerraro** [comment]
ah yes, thanks again! https://github.com/CADmium-Co/CADmium/pull/19
