### ISSUE TITLE
Why are the messages not generated by rust?

### ISSUE THREAD

**Issue by dzervas** [CADmium-Co/CADmium#22]
At this point the `Message` enum and trivial methods around it are handwritten all over the project:
- the `project::Message` rust enum
- the `Message` TS type in types.d.ts (which is not the same as `Message_GeneratedFromRust`)
- most of the typeGuards functions
- more?

is that a design choice for some reason?

My thought was to have a single point of truth (rust) and then auto-generate everything else (using macros, build scripts, you name it). Any reason NOT to sink my time into that/design constraints?

**Comment by av8ta** [comment]
@dzervas this is all changing soon with the new work going into the oplog and evolution tree so would be a good reason not to sink your time into that right now! Agree with what you've said though! initially the project did not have a message passing api which was later added, then after that the front end was converted from javascript to typescript. the new oplog work will change it again; this time with the oplog providing a focus on what happened, like an event sourcing system, rather being focused on state as the codebase currently is.

**Comment by dzervas** [comment]
awesome!
