### ISSUE TITLE
Rectangle Tool does not stop after finishing Rectangle

### ISSUE THREAD

**Issue by MattFerraro** [CADmium-Co/CADmium#68]
Currently, when editing a sketch you can tap "r" to activate the rectangle tool. You can click once to place the first point, then as you move the mouse around you can preview the rectangle as you decide where to place the second point. Upon clicking the second point, the rectangle is completed and gets added to the sketch correctly.

What _should_ happen next is that you should continue to be in rectangle mode, but your mouse pointer should now be completely free: you should choosing where to place the _first_ point of a new rectangle.

Instead what happens now is that the first point of the first rectangle seems to stay selected and your mouse cursor is already previewing a second rectangle.

**Comment by huangxiaobao-cxx** [comment]
I will complete this issue!

**Comment by huangxiaobao-cxx** [comment]
I created hte PR https://github.com/CADmium-Co/CADmium/pull/88 with the solution.

Now after using the rectangular tool, if the rectangle is continued, the first point of the rectangle will be re -drawed. I passed the local test.

**Comment by MattFerraro** [comment]
Thank you!
