### ISSUE TITLE
Escape Key should exit sketch tool without escaping full screen mode (Firefox only bug)

### ISSUE THREAD

**Issue by MattFerraro** [CADmium-Co/CADmium#69]
When I'm using any of the sketch tools like rectangle or circle or line, I expect to be able to cancel the current rectangle/circle/line by tapping the escape key. This does work on both Chrome and Firefox, but specifically on Firefox if my browser is full screen the escape switches the browser back into partial-screen mode. This is super annoying because then the page resizes and everything reflows. This does not happen on Chrome

Expected behavior is that escape key should not switch the browser from full screen mode to partial screen mode.

I have only seen this behavior on Firefox on a Mac

**Comment by 0HyperCube** [comment]
It is currently impossible to override the standard firefox escape behaviour as this could allow malicious sites to mislead or trap the user. There is [some unresolved discussion](https://github.com/whatwg/fullscreen/issues/231) on blocking the keyboard inputs for this usecase. There is also a chromium only [keyboard lock api](https://github.com/WICG/keyboard-lock) that resolves this, but nothing yet for firefox.

**Comment by MattFerraro** [comment]
ouch, that's a big bummer. I guess I'll close this for now then!
