### ISSUE TITLE
Remove unused UI components

### ISSUE THREAD

**Issue by MattFerraro** [CADmium-Co/CADmium#70]
The "mattferraro.dev" in the upper right corner is a placeholder that will one day hold the user's own username. For now it is unused and should be removed.

The "Solve" and "Step" buttons are a holdover from a previous experiment building an iterative 2D constraint solver. They are no longer necessary and should be removed.

**Comment by jasonmokk** [comment]
Hello, can I work on this issue?

**Comment by bhiwagade-rahul** [comment]
@MattFerraro  I have not found  "Solve" and "Step" buttons, can you please explain where it is?

**Comment by av8ta** [comment]
> @MattFerraro I have not found "Solve" and "Step" buttons, can you please explain where it is?

if you search for "solve" you will find it.

I already put this PR through. If you were wanting to add more to it, it would have been better as a draft, or just wait until you have it done before raising the PR. All good if PRs are small changes like this one though :+1:
