### ISSUE TITLE
Add a Favicon

### ISSUE THREAD

**Issue by MattFerraro** [CADmium-Co/CADmium#74]
On Firefox on a Mac, the favicon for CADmium seems to be absent. On Chrome it looks like a globe which I suspect is the default favicon when the page doesn't provide one.

Let's make the project logo the favicon!

**Comment by GonBlank** [comment]
i will thake this issue!

**Comment by GonBlank** [comment]
**I created hte PR #82 with the solution.**

The project logo has a white background, it would be a good practice to use the logo without a background as a favicon. If you want to change the image you can comment here and I will update it.

**Comment by av8ta** [comment]
I already merged your PR @GonBlank but agree, would be better without the white background :pray:

**Comment by GonBlank** [comment]
I made PR #84 with the new set of faicons without the white background 🤘

**Comment by MattFerraro** [comment]
Thank you @GonBlank!
